name: aistudio-to-api

services:
  app:
    image: aistudio-to-api-custom:latest
    container_name: aistudio-to-api
    ports:
      - "192.168.0.104:8317:7860"
      - "192.168.0.104:9998:9998"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./configs/auth:/app/configs/auth
      - ./data:/app/data
    environment:
      HTTP_PROXY: "http://host.docker.internal:7890"
      HTTPS_PROXY: "http://host.docker.internal:7890"
      NO_PROXY: "localhost,127.0.0.1,::1"
      API_KEYS: "sk-123456"
      TZ: "Asia/Shanghai"
      LOG_LEVEL: "DEBUG"
      MAX_CONTEXTS: "2"

